sudo: false

language: go

git:
  depth: 1

go:
  - 1.12.x

# workaround to hide repo author from the code
install:
  - cd ../..
  - mkdir devchallenge
  - mv $TRAVIS_REPO_SLUG devchallenge/spy-api
  - cd devchallenge/spy-api

services:
  docker

script:
  - make test
  - make docker

notifications:
  email:
    on_success: never
    on_failure: always
