sudo: false

language: go

git:
  depth: 1

go:
  - 1.12.x

# workaround to hide repo author from the code
install:
  - cd ../..
  - mkdir devchallenge
  - mv alexandear/spy-api devchallenge/spy-api
  - cd devchallenge/spy-api

services:
  docker

before_script:
  - make build
  - make test

script:
  - make docker

notifications:
  email:
    on_success: never
    on_failure: always
