// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddLocationOKCode is the HTTP code returned for type AddLocationOK
const AddLocationOKCode int = 200

/*AddLocationOK OK

swagger:response addLocationOK
*/
type AddLocationOK struct {
}

// NewAddLocationOK creates AddLocationOK with default headers values
func NewAddLocationOK() *AddLocationOK {

	return &AddLocationOK{}
}

// WriteResponse to the client
func (o *AddLocationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddLocationInternalServerErrorCode is the HTTP code returned for type AddLocationInternalServerError
const AddLocationInternalServerErrorCode int = 500

/*AddLocationInternalServerError General server error

swagger:response addLocationInternalServerError
*/
type AddLocationInternalServerError struct {
}

// NewAddLocationInternalServerError creates AddLocationInternalServerError with default headers values
func NewAddLocationInternalServerError() *AddLocationInternalServerError {

	return &AddLocationInternalServerError{}
}

// WriteResponse to the client
func (o *AddLocationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
