// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBboutputOKCode is the HTTP code returned for type GetBboutputOK
const GetBboutputOKCode int = 200

/*GetBboutputOK OK

swagger:response getBboutputOK
*/
type GetBboutputOK struct {
}

// NewGetBboutputOK creates GetBboutputOK with default headers values
func NewGetBboutputOK() *GetBboutputOK {

	return &GetBboutputOK{}
}

// WriteResponse to the client
func (o *GetBboutputOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
