// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOurellBbinputHandlerFunc turns a function with the right signature into a post ourell bbinput handler
type PostOurellBbinputHandlerFunc func(PostOurellBbinputParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOurellBbinputHandlerFunc) Handle(params PostOurellBbinputParams) middleware.Responder {
	return fn(params)
}

// PostOurellBbinputHandler interface for that can handle valid post ourell bbinput params
type PostOurellBbinputHandler interface {
	Handle(PostOurellBbinputParams) middleware.Responder
}

// NewPostOurellBbinput creates a new http.Handler for the post ourell bbinput operation
func NewPostOurellBbinput(ctx *middleware.Context, handler PostOurellBbinputHandler) *PostOurellBbinput {
	return &PostOurellBbinput{Context: ctx, Handler: handler}
}

/*PostOurellBbinput swagger:route POST /ourell/bbinput postOurellBbinput

TODO

TODO

*/
type PostOurellBbinput struct {
	Context *middleware.Context
	Handler PostOurellBbinputHandler
}

func (o *PostOurellBbinput) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOurellBbinputParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
