// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostBbinputOKCode is the HTTP code returned for type PostBbinputOK
const PostBbinputOKCode int = 200

/*PostBbinputOK OK

swagger:response postBbinputOK
*/
type PostBbinputOK struct {
}

// NewPostBbinputOK creates PostBbinputOK with default headers values
func NewPostBbinputOK() *PostBbinputOK {

	return &PostBbinputOK{}
}

// WriteResponse to the client
func (o *PostBbinputOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostBbinputInternalServerErrorCode is the HTTP code returned for type PostBbinputInternalServerError
const PostBbinputInternalServerErrorCode int = 500

/*PostBbinputInternalServerError General server error

swagger:response postBbinputInternalServerError
*/
type PostBbinputInternalServerError struct {
}

// NewPostBbinputInternalServerError creates PostBbinputInternalServerError with default headers values
func NewPostBbinputInternalServerError() *PostBbinputInternalServerError {

	return &PostBbinputInternalServerError{}
}

// WriteResponse to the client
func (o *PostBbinputInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
