// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOurellBbinputOKCode is the HTTP code returned for type PostOurellBbinputOK
const PostOurellBbinputOKCode int = 200

/*PostOurellBbinputOK OK

swagger:response postOurellBbinputOK
*/
type PostOurellBbinputOK struct {
}

// NewPostOurellBbinputOK creates PostOurellBbinputOK with default headers values
func NewPostOurellBbinputOK() *PostOurellBbinputOK {

	return &PostOurellBbinputOK{}
}

// WriteResponse to the client
func (o *PostOurellBbinputOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
