// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostBbinputHandlerFunc turns a function with the right signature into a post bbinput handler
type PostBbinputHandlerFunc func(PostBbinputParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBbinputHandlerFunc) Handle(params PostBbinputParams) middleware.Responder {
	return fn(params)
}

// PostBbinputHandler interface for that can handle valid post bbinput params
type PostBbinputHandler interface {
	Handle(PostBbinputParams) middleware.Responder
}

// NewPostBbinput creates a new http.Handler for the post bbinput operation
func NewPostBbinput(ctx *middleware.Context, handler PostBbinputHandler) *PostBbinput {
	return &PostBbinput{Context: ctx, Handler: handler}
}

/*PostBbinput swagger:route POST /bbinput postBbinput

TODO

TODO

*/
type PostBbinput struct {
	Context *middleware.Context
	Handler PostBbinputHandler
}

func (o *PostBbinput) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBbinputParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
