// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Monitoring for the mobile phones' moves",
    "title": "Spy API",
    "version": "1.0.0"
  },
  "basePath": "/ourell",
  "paths": {
    "/bbinput": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "summary": "Accepts GPS coordinates from the mobile and saves to database",
        "operationId": "addLocation",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "number",
                "imei",
                "coordinates"
              ],
              "properties": {
                "coordinates": {
                  "description": "GPS coordinates of the phone's location",
                  "type": "array",
                  "items": {
                    "type": "number",
                    "format": "float"
                  }
                },
                "imei": {
                  "description": "Device identificator",
                  "type": "string"
                },
                "ip": {
                  "description": "Optional IP address",
                  "type": "string"
                },
                "number": {
                  "description": "Phone",
                  "type": "string"
                },
                "timestamp": {
                  "description": "EET timestamp in \"YYYY/MM/DD-hh:mm:ss\" format",
                  "type": "string"
                }
              },
              "example": {
                "coordinates": [
                  22.1832284135991,
                  60.4538416572538
                ],
                "imei": "502507345219189",
                "ip": "35.25.21.123",
                "number": "+380991926482",
                "timestamp": "2019/03/22-15:50:20"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "General server error"
          }
        }
      }
    },
    "/bboutput": {
      "get": {
        "description": "TODO",
        "produces": [
          "application/json"
        ],
        "summary": "TODO",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Monitoring for the mobile phones' moves",
    "title": "Spy API",
    "version": "1.0.0"
  },
  "basePath": "/ourell",
  "paths": {
    "/bbinput": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "summary": "Accepts GPS coordinates from the mobile and saves to database",
        "operationId": "addLocation",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "number",
                "imei",
                "coordinates"
              ],
              "properties": {
                "coordinates": {
                  "description": "GPS coordinates of the phone's location",
                  "type": "array",
                  "items": {
                    "type": "number",
                    "format": "float"
                  }
                },
                "imei": {
                  "description": "Device identificator",
                  "type": "string"
                },
                "ip": {
                  "description": "Optional IP address",
                  "type": "string"
                },
                "number": {
                  "description": "Phone",
                  "type": "string"
                },
                "timestamp": {
                  "description": "EET timestamp in \"YYYY/MM/DD-hh:mm:ss\" format",
                  "type": "string"
                }
              },
              "example": {
                "coordinates": [
                  22.1832284135991,
                  60.4538416572538
                ],
                "imei": "502507345219189",
                "ip": "35.25.21.123",
                "number": "+380991926482",
                "timestamp": "2019/03/22-15:50:20"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "General server error"
          }
        }
      }
    },
    "/bboutput": {
      "get": {
        "description": "TODO",
        "produces": [
          "application/json"
        ],
        "summary": "TODO",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
}
