swagger: "2.0"
info:
  title: Spy API
  version: 1.0.0
basePath: /ourell
schemes:
  - http
paths:
  /bbinput:
    post:
      summary: TODO
      description: TODO
      produces:
        - application/json
      responses:
        200:
          description: OK

  /bboutput:
    get:
      summary: TODO
      description: TODO
      produces:
        - application/json
      responses:
        200:
          description: OK
