swagger: "2.0"
info:
  title: Spy API
  version: "1.0.0"
  description: Monitoring for the mobile phones' moves
basePath: /ourell
schemes:
  - http
paths:
  /bbinput:
    post:
      summary: Accepts GPS coordinates from the mobile and saves them to the database
      consumes:
        - application/json
      operationId: addLocation
      parameters:
        - in: body
          name: body
          schema:
            type: object
            example:
              number: "+380991926482"
              ip: "35.25.21.123"
              imei: "502507345219189"
              timestamp: "2019/03/22-15:50:20"
              coordinates: [22.1832284135991, 60.4538416572538]
            properties:
              number:
                type: string
                description: Phone
              imei:
                type: string
                description: Device identificator
              ip:
                type: string
                description: Optional IP address
              timestamp:
                type: string
                description: EET timestamp in "YYYY/MM/DD-hh:mm:ss" format
              coordinates:
                description: GPS coordinates of the phone's location
                type: object
                properties:
                  longitude:
                    description: Longitude in degrees
                    type: number
                    format: float
                    minimum: -180
                    maximum: 180
                  latitude:
                    description: Latitude in degrees
                    type: number
                    format: float
                    minimum: -90
                    maximum: 90
            required:
              - number
              - imei
              - coordinates
      responses:
        200:
          description: OK
        400:
          description: >-
            Invalid arguments.
            Error codes:
              - 2001 - wrong number
              - 2002 - empty IMEI
              - 2003 - bad coordinates
              - 2004 - wrong timestamp format
              - 2005 - wrong IP
          schema:
            $ref: '#/definitions/Error'
        500:
          description: General server error
          schema:
            $ref: '#/definitions/Error'

  /bboutput:
    get:
      summary: TODO
      description: TODO
      produces:
        - application/json
      responses:
        200:
          description: OK

definitions:
  # Schema for error response body
  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
